Objetivo 4
danifm1321/proyectoIV pull request #12
Opened 2021-11-11 08:33 UTC by danifm1321

Desarrollo del código suficiente para realizar tests, y creación de los tests como tal.

2021-11-15 21:25 UTC, danifm1321 commented
@JJ listo para revisión, aunque tengo dudas de si debería haber implementado mas lógica de negocio antes de crear los tests.

2021-11-16 09:16 UTC, JJ commented
El lun, 15 nov 2021 a las 22:25, Daniel Fernández Mérida (<
***@***.***>) escribió:

> @JJ <https://github.com/JJ> listo para revisión, aunque tengo dudas de si
> debería haber implementado mas lógica de negocio antes de crear los tests.
>

Tienes que implementar _algo_.

2021-11-17 19:45 UTC, danifm1321 commented
@JJ listo para revisión

2021-11-18 06:54 UTC, JJ requested changes
Todavía te falta un poco. Dale una vuelta, por favor.

2021-11-18 06:54 UTC, JJ commented on anime/anime.py
> +from aenum import Enum, NoAlias      #Biblioteca para que varios enum puedan tener los mismos valores sin problemas
??? Conviene en este punto no añadir varias bibliotecas.

2021-11-18 06:54 UTC, JJ commented on anime/anime.py
> +    ROMANCE = 70
Justifica esto, por favor. Si se trata de que tengan cercanía los que sean parecidos, justifícalo.

2021-11-18 06:54 UTC, JJ commented on anime/anime.py
> +    SLIECEOFLIFE = 60
typo

2021-11-18 06:54 UTC, JJ commented on anime/anime.py
> +        self.visualizaciones += 1
visualizaciones == calificaciones?

2021-11-18 06:54 UTC, JJ commented on anime/anime.py
> +        self.visualizaciones += 1
Also, single responsability principle

2021-11-18 06:54 UTC, JJ commented on anime/recomendacion.py
> +    return recom[1]
??

2021-11-18 06:54 UTC, JJ commented on anime/recomendacion.py
> +            for gen in ani.generos:
Puedes usar map-reduce para esto'

2021-11-18 06:54 UTC, JJ commented on anime/usuario.py
> +        self.contrasena = contrasena
Ya os dije lo de la contraseña.

2021-11-18 06:54 UTC, JJ commented on docs/Objetivo4.md
> +Se ha utilizado pytest para la ejecución de los tests debido a su sencillez y comodidad, además de que contiene todo lo necesario para el desarrollo de la práctica, pudiendo manejar el lanzamiento de
No dices nada de la biblioteca de aserciones. Y "sencillez" y "comodidad" no son parámetros técnicos para elección de nada.

2021-11-18 06:54 UTC, JJ commented on pyproject.toml
>  pylint = "^2.11.1"
Esto debería estar en devDependencies

2021-11-18 06:54 UTC, JJ commented on tests/test_recomendaciones.py
> +user = Usuario("danifm13", "admin")
Agh, clave en texto plano...

2021-11-18 06:54 UTC, JJ commented on tests/test_recomendaciones.py
> +    for i in range(len(user.recomendaciones)-1):
Usa map o usa un bucle sobre los propios elementos.

2021-11-18 06:54 UTC, JJ commented on tests/test_recomendaciones.py
> +    assert len(recomendaciones) == 0       #No hay actualmente animes con ese género, las recomendaciones deberían ser 0
No estás usando más que la palabra clave "assert", sin ninguna biblioteca de aserciones. Por favor, elige y usa una.

2021-11-21 23:19 UTC, danifm1321 commented
@JJ listo para revision

2021-11-22 11:08 UTC, JJ requested changes
Aparte de las recomendaciones indicadas, el problema principal es que no usas la biblioteca de aserciones que dices que usas que, además, no es una biblioteca de aserciones. Por favor, infórmate un poco sobre aserciones en Python y corrige tanto la documentación como el código.

2021-11-22 11:08 UTC, JJ commented on anime/anime.py
> +    Los valores se han elegido en función a lo concreto que sea el género. Por ejemplo, el género ACTION (acción) es un género que considero más secundario, que se puede poner más a la ligera en una
¿Ves lo que pasa con los comentarios? Si pones las decisiones que has tomado aquí en vez de en un mensaje de commit, corres el riesgo de que se queden obsoletas rápidamente. Este tipo de comentarios sí son aceptables en código limpio, pero sólo si son documentación de la clase a la hora de generarla.

2021-11-22 11:08 UTC, JJ commented on anime/anime.py
> +    recalcula_media(nota)
Por ejemplo, esto sí sería válido (si el formato está bien)

2021-11-22 11:08 UTC, JJ commented on anime/anime.py
> +        '''
¿Seguro que esto no es detrás del `def`?

2021-11-22 11:08 UTC, JJ commented on docs/Objetivo4.md
> +La biblioteca de aserciones ha sido la proporcionada por pytest, que tiene lo necesario para el desarrollo de los tests del objetivo, pudiendo evaluar las expresiones necesarias y, en caso de que sea
`pytest` sólo proporciona fixtures y algún test de excepciones. A ver lo que has usado...

2021-11-22 11:08 UTC, JJ commented on tests/test_recomendaciones.py
> +    assert len(user.vistos) == 0
Esto no es de `pytest`, es una palabra clave de Python. Por favor, aclárate en qué usas para las aserciones. ¿Qué otras bibliotecas de aserciones has visto?

2021-11-22 17:34 UTC, JJ approved these changes
Por favor, a partir de ahora haced las justificaciones de forma que no sean un anuncio de lo que ya habéis decidido. Mostrar lo que habéis visto y justificar la elección. Por otro lado, hay una serie de comentarios que podrías solucionar antes del paso siguiente.

2021-11-22 17:34 UTC, JJ commented on docs/Objetivo4.md
> +La biblioteca de aserciones a utilizar seria assertpy. Esta biblioteca esta recomendada por los propios [desarrolladores](https://github.com/assertpy/assertpy) para ser usada junto con pytest. Permit
Tampoco lo has justificado. También está `unittest` y otras...

2021-11-22 17:45 UTC, merged