[IV-21-22] Objetivo 5
danifm1321/proyectoIV pull request #18
Opened 2021-12-03 20:58 UTC by danifm1321

Realización del objetivo 5, que comprende la creación de una imagen de docker, con el fin de realizar un despliegue mas sencillo de nuestra aplicación en la nube, y la automatización de la actualización de nuestra imagen de docker en Dockerhub mediante el uso de Github Actions

2021-12-03 21:18 UTC, danifm1321 commented
@JJ listo para revision

2021-12-07 17:34 UTC, JJ requested changes
Al final ha tocado revisar en el puente. Y a ti también... Dale una vuelta a ver si lo tienes a la siguiente.

2021-12-07 17:34 UTC, JJ commented on .github/workflows/update_docker.yml
> +      - name: Extract metadata (tags, labels) for Docker
¿Esto sirve para algo?

2021-12-07 17:34 UTC, JJ commented on .github/workflows/update_docker.yml
> +          labels: ${{ steps.meta.outputs.labels }}
ya vimos en clase lo que se había que poner aquí. Conviene que los ejemplos los toméis siempre con un grano de sal y tratéis de entender lo que hacen.

2021-12-07 17:34 UTC, JJ commented on Dockerfile
> +LABEL manteiner="danifm1321"
Agh, typo.

2021-12-07 17:34 UTC, JJ commented on Dockerfile
> +RUN pip3 install poetry; poetry config virtualenvs.create false; poetry install
De verdad que no sé por qué ponéis lo de virtualenvs, salvo que todo el mundo lo hacéis. Tendréis que explicar de dónde lo sacáis, y qué pasa si lo quitáis.

2021-12-07 17:34 UTC, JJ commented on docs/Objetivo5.md
> +Para el desarrollo del objetivo 5 se ha elegido el contenedor Docker.
Tienes que decir qué contenedor base has elegido, no que has elegido el contenedor Docker, que es lo que os pide el objetivo.

2021-12-07 18:35 UTC, danifm1321 commented on Dockerfile
> +RUN pip3 install poetry; poetry config virtualenvs.create false; poetry install
En caso de que no esté esa opción, poetry instala las dependencias en su entorno virtual. Poniendo esta opción, instala las dependencias en el entorno virtual creado por el propio docker. Si no se pone la opción a la hora de ejecutar el contenedor da un error de que no se encuentra, en mi caso, invoke.

2021-12-07 18:50 UTC, JJ commented on Dockerfile
> +RUN pip3 install poetry; poetry config virtualenvs.create false; poetry install
No, no se hace eso. Y si no encuentra invoke es porque no estará en el path. No tiene nada que ver con poetry.

2021-12-07 20:35 UTC, danifm1321 commented
@JJ listo para revision

2021-12-08 12:22 UTC, JJ requested changes
Sigue sin tratarse de "averiguar" qué imagen poner. Se trata de que mostréis que sois capaces de tomar decisiones técnicas, que comprometan al desarrollo de un proyecto de ese momento en adelante.

2021-12-08 12:22 UTC, JJ commented on .github/workflows/update_docker.yml
> +      - 'main'
¿Y qué pasa si cambia en otra rama?

2021-12-08 12:22 UTC, JJ commented on docs/Objetivo5.md
> +La imagen a usar debe ser una imagen ligera que facilite el despliegue posterior de la aplicación. En ese caso, -slim contiene lo mínimo para correr python, lo cual la convierte en una fuerte candida
¿Frente a qué otras candidatas? ¿Las otras no contienen lo mínimo para correr python?

2021-12-08 12:57 UTC, danifm1321 commented on .github/workflows/update_docker.yml
> +      - 'main'
Por lo que tengo entendido, si cambia en otra rama no se reconstruye la imagen en dockerhub. Lo había planteado de esa manera, que la imagen solo se reconstruya cuando haya cambios en main, ya que en main son cambios "definitivos" y en otras ramas son cambios "en desarrollo".

2021-12-09 10:17 UTC, danifm1321 commented
@JJ listo para revisión, he añadido un poco más acerca de la decisión de usar python slim.

2021-12-09 19:25 UTC, JJ commented on .github/workflows/update_docker.yml
> +      - 'main'
Si vas a usarlo para test, ¿no vas a testear lo de las ramas?

2021-12-09 19:28 UTC, JJ approved these changes
Realmente no has hecho una buena comparación, pero no quiero retrasarte más. Por favor, sigue a partir de ahora los criterios que hoy (y otras veces) he explicado en clase.

2021-12-09 19:28 UTC, JJ commented on docs/Objetivo5.md
> +La imagen a usar debe ser una imagen ligera que facilite el despliegue posterior de la aplicación. Por lo tanto, la imagen completa de python fue descartada, siendo demasiado pesada. En ese caso, -sl
¿Qué imagen completa? ¿Cuanto pesa?

2021-12-09 19:28 UTC, JJ commented on docs/Objetivo5.md
> +La otra imagen considerada como candidata sería -alpine, sin embargo -alpine es propenso a errores complicados de localizar y tiene mayores tiempos a la hora de construir la imagen, por lo que tome l
¿Qué errores? Si vais a decir estas cosas, tenéis que justificarlas con algo que sea de vuestro propio proyecto. En general, Alpine funciona perfectamente.
Y por supuesto, puedes optar por instalar tú mismo Python o usar imágenes que no sean oficiales.

2021-12-09 19:28 UTC, JJ commented on docs/Objetivo5.md
> +Debido a que con el uso de docker ya tenemos un entorno virtual, no es necesario crear el de poetry. Tras investigar acerca de la creación de Dockerfiles que incluyan poetry, he llegado a la conclusi
No sé qué decirte. Si eso ahorra algo, puede ser. Pero ¿ahorra espacio? ¿Lo habéis probado?

2021-12-10 12:06 UTC, merged