[IV 21-22] Objetivo 6
danifm1321/proyectoIV pull request #20
Opened 2021-12-15 17:31 UTC by danifm1321

Elección y desarrollo de un sistema de integración continua que nos permita asegurar el código.

2021-12-15 19:09 UTC, danifm1321 commented
@JJ listo para revision

2021-12-16 01:16 UTC, alexespana requested changes
Buenas @danifm1321 , a pesar de no ser un revisor aleatorio de este PR, he querido ayudarte para que puedas superar el objetivo. Sólo tienes un sistema de integración continua, que es CircleCI, con éste **testeas la aplicación** con distintas versiones del lenguaje (ver comentarios), pero te faltaría otro con el que ejecutar los tests automáticamente (ten en cuenta que debes de aprovechar cosas del objetivo anterior para esto :wink: ) Échale un ojo a los comentarios que te hice. :smile:

2021-12-16 01:16 UTC, alexespana commented on docs/Objetivo6.md
> +Para nuestro sistema de integraición continua tenemos dos requisitos básicos: que sea compatible con github, nuestra plataforma de control de versiones, y que sea en la nube, es decir, online.
Sinceramente, creo que los requisitos podrían ser más concretos, algo más específico que busques en un Sistema de CI, por ejemplo, que sea gratuito, que tenga checks API con github, etc, a lo que me refiero..., que sea online lo cumplen todos los sistemas de integración continua, ya que se debe verificar la calidad del código cada vez que se pushea al repositorio

2021-12-16 09:21 UTC, danifm1321 commented
@alexespana muchas gracias, por echarle un ojo a mi pull request, aún así no me ha quedado una cosa clara. Dices que hace falta que pase los tests automáticamente, pero actualmente cada vez que realizo un commit se pasan mis tests, ¿no se refiere a eso con pasar los tests automáticamente?

2021-12-16 09:46 UTC, alexespana commented
> @alexespana muchas gracias por echarle un ojo a mi pull request, aún así no me ha quedado una cosa clara. Dices que hace falta que pase los tests automáticamente, pero actualmente cada vez que realizo un commit se pasan mis tests, ¿no se refiere a eso con pasar los tests automáticamente?

¿Más bien sería cuando se hace push al repo no? Realmente no, tú ahora mismo lo que estás haciendo es testear la aplicación con distintas versiones del lenguaje, que es verdad que este testeo se hace en cada push, pero aparte debes de pasar los tests cada vez que se añada código a tu repositorio, que no es el testeo de las versiones.

Por esta razón, debes elegir otro sistema de CI con el que realizar esto. Si te fijas, en la lista de comprobación del objetivo, hay un punto que dice:
* [ ]  ¿Se han configurado varios sistemas de integración continua?

Cualquier duda pregúntame!

2021-12-16 09:51 UTC, danifm1321 commented
Entiendo, muchas gracias!

2021-12-16 12:30 UTC, danifm1321 commented
Listo para revision

2021-12-16 12:33 UTC, JJ commented
> @alexespana muchas gracias por echarle un ojo a mi pull request, aún así no me ha quedado una cosa clara. Dices que hace falta que pase los tests automáticamente, pero actualmente cada vez que realizo un commit se pasan mis tests, ¿no se refiere a eso con pasar los tests automáticamente?

Creo que quiere decir también *pasar los tests de la asignatura* y para eso tienes que pasar los tests con un contenedor, que es también un requisito de este objetivo.

2021-12-16 12:40 UTC, danifm1321 commented
> > @alexespana muchas gracias por echarle un ojo a mi pull request, aún así no me ha quedado una cosa clara. Dices que hace falta que pase los tests automáticamente, pero actualmente cada vez que realizo un commit se pasan mis tests, ¿no se refiere a eso con pasar los tests automáticamente?
> 
> Creo que quiere decir también _pasar los tests de la asignatura_ y para eso tienes que pasar los tests con un contenedor, que es también un requisito de este objetivo.

En el último commit ya incluyo una github action que pasa los tests a través del contenedor, gracias por el apunte.

2021-12-16 16:10 UTC, JJ requested changes
Debes tratar de entender un poco mejor lo que estás haciendo. Ánimo que casi lo tienes.

2021-12-16 16:10 UTC, JJ commented on .circleci/config.yml
> +          command: pip3 install poetry; poetry config virtualenvs.create false; poetry install; invoke test
Agh, otra vez lo mismo de virtualenvs. ¿Qué más da que los cree?

2021-12-16 16:10 UTC, JJ commented on .github/workflows/continuous_integration.yml
> +      - name: Setup Python
¿Por qué necesitas esto? ¿Has comprobado que de verdad haga falta?

2021-12-16 16:10 UTC, JJ commented on docs/Objetivo6.md
> +He testeado las versiones 3.8 y 3.9 de python, ya que mi proyecto fue originalmente planteado para python 3.8, al ser una versión actual y asentada. Partiendo de ahí, he decidido testear versiones po
Tienes que probar no la versión "actual y asentada". Se trata que descubras cuál es la versión mínima de Python que tu proyecto soporta, o porque lo sepas porque usas lo que sea de Python que sólo va a partir de no sé qué versión o porque lo testees. Hemos repetido en clase muchas veces qué versiones se testean y por qué.

2021-12-16 18:53 UTC, danifm1321 commented on .github/workflows/continuous_integration.yml
> +      - name: Setup Python
Tienes razón, al usar el docker no necesito el setup de python, no me había dado cuenta.

2021-12-16 20:47 UTC, danifm1321 commented
Listo para revisión

2021-12-16 21:01 UTC, alexespana approved these changes
En general, creo que está bastante mejorado. Podría pasar el objetivo, por esta razón le doy el visto bueno yo, aunque como te comenté anteriormente, los requisitos para elegir los sistemas de CI me parecen débiles.

2021-12-17 06:39 UTC, JJ requested changes
El milestone al que está asignado es demasiado genérico, y no incluye este desarrollo.

2021-12-17 06:42 UTC, JJ requested changes
Aparte de lo que comento, el principal problema ahora mismo es el milestone al que está asignado.

2021-12-17 06:42 UTC, JJ commented on docs/Objetivo6.md
> +También consideraremos usar CircleCI. CircleCI funciona sin plugins externos, y podemos definir un archivo yml que lea cada vez que realicemos el push. Además tiene su propio validador de yaml que no
... y peta con cierta frecuencia.

2021-12-17 06:42 UTC, JJ commented on docs/Objetivo6.md
> +Se han tenido en cuenta Jenkins y TeamCity, dos herramientas de integración continua muy potentes. Sobre todo TeamCity, ya que tiene una versión gratuita con una interfaz visual bastante atractiva y
¿Cómo se han tenido en cuenta? ¿Te puedes abrir una cuenta de Jenkins CI gratuita? ¿Lo habéis mirado de verdad?

2021-12-17 07:40 UTC, danifm1321 commented on docs/Objetivo6.md
> +Se han tenido en cuenta Jenkins y TeamCity, dos herramientas de integración continua muy potentes. Sobre todo TeamCity, ya que tiene una versión gratuita con una interfaz visual bastante atractiva y
Sí, Jenkins es un proyecto de código abierto y software libre, así que puedes usarlo gratuitamente

2021-12-17 08:18 UTC, danifm1321 commented
Milestone cambiado

2021-12-17 10:32 UTC, JJ commented on docs/Objetivo6.md
> +Se han tenido en cuenta Jenkins y TeamCity, dos herramientas de integración continua muy potentes. Sobre todo TeamCity, ya que tiene una versión gratuita con una interfaz visual bastante atractiva y
... si te lo instalas y por tanto no es comparable al resto. No se trata de que pongáis cosas que hayáis leído por ahí, sino que realmente evaluéis vosotros diferentes alternativas *reales* para vuestro proyecto.

2021-12-17 10:35 UTC, JJ requested changes
No es muy buena la explicación de los sistemas elegidos (ayer mismo dijiste que CircleCI estaba caído) ni de las versiones que has elegido. No está claro tampoco que una de las versiones que pruebas en Circle no esté ya incluida en la imagen Docker.
Como siempre, es esencial que entendáis lo que estáis haciendo y por qué y que demostréis que lo entendéis con la documentación del objetivo.

2021-12-17 10:35 UTC, JJ commented on .circleci/config.yml
> +              python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
No se trata de que probéis todo lo que se os ocurra. Cada test cuesta dinero. Por favor, seguid un criterio para elegir las versiones que vayáis a probar.

2021-12-17 18:43 UTC, danifm1321 commented
Pero aunque CircleCI se cayera ayer, sigue teniendo una disponibilidad por encima del 99%, que una herramienta se haya caido puntualmente no me parece un criterio significativo para descartarla.

2021-12-17 18:45 UTC, danifm1321 commented on docs/Objetivo6.md
> +Se han tenido en cuenta Jenkins y TeamCity, dos herramientas de integración continua muy potentes. Sobre todo TeamCity, ya que tiene una versión gratuita con una interfaz visual bastante atractiva y
Tanto para TeamCity como para Jenkins es necesario una instalación, pero no creía que eso ya las hacía incomparables al resto. Por eso acabaron descartadas, porque para esos dos sistemas es necesaria una instalación, mientras que para las github actions o para circleCi es únicamente un archivo. A eso me refería con la sencillez a la hora de ser implementados en nuestro proyecto.

2021-12-17 19:15 UTC, danifm1321 commented
Eleccion de las versiones a utilizar actualizada

2021-12-17 19:17 UTC, JJ commented on docs/Objetivo6.md
> +Se han tenido en cuenta Jenkins y TeamCity, dos herramientas de integración continua muy potentes. Sobre todo TeamCity, ya que tiene una versión gratuita con una interfaz visual bastante atractiva y
Si son incomparables, ¡no las pongas!

2021-12-17 19:17 UTC, JJ approved these changes
:+1:

2021-12-19 11:05 UTC, merged